version: '3.8'

services:
  sentiment-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
